// Copyright (c) 2026 Federico Pereira <lord.basex@gmail.com>
// Builds go-link's CPS-1 prototype into a ROM set the mame2003-plus core
// runs: compiles the 68000 program (C + start-up) and the Z80 program,
// draws the graphics into the CPS-1 graphics ROM format, and lays every
// file out with the names and sizes of a set of the core's driver (all
// bytes ours).
//
//   node rom/tools/build.mjs [set]   -> rom/build/<set>.zip
//
// Sets: slammast (default: 4 players x 3 buttons, QSound board) and
// captcomm (4 players x 2 buttons, the first prototype). See
// docs/rom/journal.md, step 0b.
//
// Needs m68k-elf-gcc and binutils, z80asm and zip (see rom/README.md).

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { GfxRegion, solid } from "./cps1gfx.mjs";
import { glyphPixels } from "./font.mjs";
import { addArt } from "./art.mjs";
import { KEYS, encodeOpcodes } from "./kabuki.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "src");
const OUT = path.join(ROOT, "build");
const SET = process.argv[2] || "slammast";

// The layouts, from src/drivers/cps1.c (ROM_START). Program files are
// 16-bit words loaded with ROM_LOAD16_WORD_SWAP (`swap`) or byte pairs with
// ROM_LOAD16_BYTE (`even`/`odd`), at the offset `at` of the 68000 space.
const SETS = {
  captcomm: {
    program: [
      { name: "cce_23d.rom", at: 0x000000, size: 0x80000, swap: true },
      { name: "cc_22d.rom", at: 0x080000, size: 0x80000, swap: true },
      { name: "cc_24d.rom", at: 0x100000, size: 0x20000, even: true },
      { name: "cc_28d.rom", at: 0x100001, size: 0x20000, odd: true },
    ],
    gfxSize: 0x400000,
    gfx: [
      ["gfx_01.rom", "gfx_03.rom", "gfx_02.rom", "gfx_04.rom"],
      ["gfx_05.rom", "gfx_07.rom", "gfx_06.rom", "gfx_08.rom"],
    ],
    // Z80: the first 0x8000 at 0x0000, ROM_CONTINUE 0x8000 at 0x10000.
    z80: { name: "cc_09.rom", size: 0x10000, src: "sound.z80" },
    samples: [{ name: "cc_18.rom", size: 0x20000, fill: 0x80 }, { name: "cc_19.rom", size: 0x20000, fill: 0x80 }],
  },
  slammast: {
    program: [
      { name: "mbe_23e.rom", at: 0x000000, size: 0x80000, swap: true },
      { name: "mbe_24b.rom", at: 0x080000, size: 0x20000, even: true },
      { name: "mbe_28b.rom", at: 0x080001, size: 0x20000, odd: true },
      { name: "mbe_25b.rom", at: 0x0c0000, size: 0x20000, even: true },
      { name: "mbe_29b.rom", at: 0x0c0001, size: 0x20000, odd: true },
      { name: "mbe_21a.rom", at: 0x100000, size: 0x80000, swap: true },
      { name: "mbe_20a.rom", at: 0x180000, size: 0x80000, swap: true },
    ],
    gfxSize: 0x600000,
    gfx: [
      ["mb_gfx01.rom", "mb_gfx03.rom", "mb_gfx02.rom", "mb_gfx04.rom"],
      ["mb_05.bin", "mb_07.bin", "mb_06.bin", "mb_08.bin"],
      ["mb_10.bin", "mb_12.bin", "mb_11.bin", "mb_13.bin"],
    ],
    // QSound Z80: the first 0x8000 at 0x0000 (Kabuki-encrypted), then 0x18000 at 0x10000.
    z80: { name: "mb_qa.rom", size: 0x20000, src: "sound-qsound.z80", kabuki: KEYS.slammast },
    samples: Array.from({ length: 8 }, (_, i) => ({ name: `mb_q${i + 1}.bin`, size: 0x80000, fill: 0x00 })),
  },
};
const LAYOUT = SETS[SET];
if (!LAYOUT) throw new Error(`unknown set ${SET}: ${Object.keys(SETS).join(", ")}`);

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, { stdio: "inherit", ...opts });
}

function pad(buf, size, fill = 0xff) {
  if (buf.length > size) throw new Error(`does not fit: ${buf.length} > ${size}`);
  const out = Buffer.alloc(size, fill);
  buf.copy(out);
  return out;
}

// only this build's own outputs (build/room and build/quality belong to other tools)
for (const d of ["obj", "gen", SET, `${SET}.zip`, "program.map"]) fs.rmSync(path.join(OUT, d), { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "obj"), { recursive: true });
const GEN = path.join(OUT, "gen"); // generated sources: gfx.h, art_data.c, previews
fs.mkdirSync(GEN, { recursive: true });

// 1. Graphics, and the header the program uses to find them.
const gfx = new GfxRegion(LAYOUT.gfxSize);
const defs = [];
for (let c = 0x21; c < 0x60; c++) gfx.tile8(c, glyphPixels(String.fromCharCode(c)));
defs.push("#define FONT_CODE(ch) ((u16)(ch)) /* 8x8 tile code = ASCII */");
defs.push("#define TILE16_EMPTY 0x0400 /* left as pen 15 */");
gfx.tile16(0x401, solid(16, 1));
defs.push("#define TILE16_SOLID 0x0401");
defs.push("#define TILE32_EMPTY 0x0200 /* left as pen 15 */");
addArt(gfx, defs, GEN); // sprites, background tiles and palettes (art.mjs)
fs.writeFileSync(
  path.join(GEN, "gfx.h"),
  `/* Copyright (c) 2026 Federico Pereira <lord.basex@gmail.com> */\n/* Generated by rom/tools/build.mjs: do not edit. */\n#ifndef GOLINK_GFX_H\n#define GOLINK_GFX_H\n#include "hw.h"\n${defs.join("\n")}\n#endif\n`,
);

// 2. The 68000 program.
// ROM_DEBUG=1 prints the players' positions on screen (for writing test scripts)
const cflags = ["-m68000", "-O2", `-DSET_${SET.toUpperCase()}`, ...(process.env.ROM_DEBUG === "1" ? ["-DDEBUG_POS"] : []), "-I", SRC, "-I", GEN, "-ffreestanding", "-nostdlib", "-fno-builtin", "-fomit-frame-pointer", "-Wall", "-Wextra", "-Wno-unused-parameter"];
const objs = [];
const sources = [...fs.readdirSync(SRC).map((f) => path.join(SRC, f)), path.join(GEN, "art_data.c")];
for (const src of sources) {
  const f = path.basename(src);
  const obj = path.join(OUT, "obj", f.replace(/\.(c|s)$/, ".o"));
  if (f.endsWith(".c")) run("m68k-elf-gcc", [...cflags, "-c", src, "-o", obj]);
  else if (f.endsWith(".s")) run("m68k-elf-as", ["-m68000", src, "-o", obj]);
  else continue;
  objs.push(obj);
}
// crt0 first is not needed: the linker script places .vectors at 0.
const elf = path.join(OUT, "obj", "program.elf");
run("m68k-elf-gcc", [...cflags, "-T", path.join(SRC, "link.ld"), ...objs, "-lgcc", "-o", elf, "-Wl,-Map," + path.join(OUT, "program.map")]);
// A copy that gcc compiles to "move (aN)+,(d,aN,Xn)" writes one word late on
// the emulated 68000 (journal, steps 2 and 4): refuse such a program.
const disasm = execFileSync("m68k-elf-objdump", ["-d", elf], { encoding: "utf8" });
const risky = disasm.split("\n").filter((l) => {
  const m = /%(a[0-6])@\+,.*%(a[0-6])@\(/.exec(l);
  return m && m[1] === m[2];
});
if (risky.length) throw new Error(`68000 code with a post-increment source and an indexed destination on the same register:\n${risky.join("\n")}`);
const bin = path.join(OUT, "obj", "program.bin");
run("m68k-elf-objcopy", ["-O", "binary", elf, bin]);
const program = fs.readFileSync(bin);
console.log(`68000 program: ${program.length} bytes`);

// 3. The Z80 program.
const z80 = path.join(OUT, "obj", "sound.bin");
run("z80asm", ["-o", z80, path.join(SRC, LAYOUT.z80.src)]);

// 4. Every file of the set.
const files = {};
const space = pad(program, 0x200000);
for (const f of LAYOUT.program) {
  if (f.swap) {
    // ROM_LOAD16_WORD_SWAP (the loader's "reverse" flag) swaps the two
    // bytes of every word as it loads, so these files hold the program
    // with each word's bytes swapped (found in step 1: a plain file made
    // the CPU jump to 0x4804, the swapped address of a handler at 0x0448).
    const part = Buffer.from(space.subarray(f.at, f.at + f.size));
    part.swap16();
    files[f.name] = part;
  } else {
    // ROM_LOAD16_BYTE: every other byte of 2 * size bytes from `at` & ~1
    const base = f.at & ~1;
    const part = Buffer.alloc(f.size);
    for (let i = 0; i < f.size; i++) part[i] = space[base + i * 2 + (f.odd ? 1 : 0)];
    files[f.name] = part;
  }
}
Object.assign(files, gfx.split(LAYOUT.gfx));
const z80code = fs.readFileSync(z80);
let sound = pad(z80code, LAYOUT.z80.size);
if (LAYOUT.z80.kabuki) {
  // QSound boards decrypt the Z80's opcodes (Kabuki): store ours encrypted
  // so they decode to what we wrote. The padding after them never runs.
  encodeOpcodes(z80code, LAYOUT.z80.kabuki).copy(sound);
}
files[LAYOUT.z80.name] = sound;
for (const f of LAYOUT.samples) files[f.name] = Buffer.alloc(f.size, f.fill);

const dir = path.join(OUT, SET);
fs.mkdirSync(dir, { recursive: true });
for (const [name, data] of Object.entries(files)) fs.writeFileSync(path.join(dir, name), data);
const zip = path.join(OUT, `${SET}.zip`);
run("zip", ["-q", "-X", "-j", zip, ...Object.keys(files).sort().map((n) => path.join(dir, n))]);
// Keep only the zip: next to a folder of the same name the core would read the folder.
fs.rmSync(dir, { recursive: true, force: true });
console.log(`built ${zip} (${Object.keys(files).length} files)`);
