// Copyright (c) 2026 Federico Pereira <lord.basex@gmail.com>
// Builds Willy Maker's data-driven engine (rom/engine/engine.c, docs/
// willy-maker/engine.md) once, for the browser: the 68000 program, the
// engine's own sprite tiles (Willy and the recruits, the civilians, the
// Lag android, the bullet and the rocket) and the plain Z80 program, as
// one file plus a manifest with the symbol map. "Create ROM" packs a game's
// data next to it; nothing is compiled in the browser.
//
//   node rom/tools/engine.mjs            -> frontend/apps/web/public/willy-maker/engine/
//   node rom/tools/engine.mjs --check    rebuilds in rom/build/engine and fails when the
//                                        committed files differ
//
// Needs m68k-elf-gcc and binutils and z80asm (see rom/README.md).

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { GfxRegion } from "../../frontend/packages/cps1/src/index.ts";
import { addArt } from "./art.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "build", "engine");
const PUBLIC = path.resolve(ROOT, "../frontend/apps/web/public/willy-maker/engine");
const CHECK = process.argv.includes("--check");

/** The recruits' shirts (players' looks 1-3), after Willy's own (look 0). */
export const RECRUIT_SHIRTS = [
  [40, 132, 84], // green, as the prototype's
  [196, 52, 52], // red
  [52, 96, 200], // blue
];
const DATA_ADDR = 0x100000;
const SPRITE_BASE = 0x1000;

const sha = (b) => createHash("sha256").update(b).digest("hex");
const run = (cmd, args) => execFileSync(cmd, args, { stdio: ["ignore", "ignore", "inherit"] });

fs.rmSync(OUT, { recursive: true, force: true });
const GEN = path.join(OUT, "gen");
fs.mkdirSync(GEN, { recursive: true });

// 1. The engine's sprites and their C tables.
const gfx = new GfxRegion(0x600000);
const defs = ["#define FONT_CODE(ch) ((u16)(ch)) /* 8x8 tile code = ASCII */"];
const { spriteEnd } = addArt(gfx, defs, GEN, { level: false, recruits: RECRUIT_SHIRTS });
// the sprite palettes the engine's art takes (32 exist): a game's own heroes use the rest
const define = (name) => {
  const m = defs.map((l) => new RegExp(`^#define ${name} (\\d+)`).exec(l)).find(Boolean);
  if (!m) throw new Error(`gfx.h has no ${name}`);
  return Number(m[1]);
};
const spritePalettes = { used: define("OBJ_PALETTES"), recruitOffset: define("RECRUIT_PAL_OFFSET"), recruits: define("RECRUITS") };
fs.writeFileSync(
  path.join(GEN, "gfx.h"),
  `/* Copyright (c) 2026 Federico Pereira <lord.basex@gmail.com> */\n/* Generated by rom/tools/engine.mjs: do not edit. */\n#ifndef GOLINK_GFX_H\n#define GOLINK_GFX_H\n#include "hw.h"\n${defs.join("\n")}\n#endif\n`,
);

// 2. The 68000 program.
const SRC = path.join(ROOT, "src");
const ENGINE = path.join(ROOT, "engine");
const cflags = ["-m68000", "-O2", "-DSET_SLAMMAST", "-I", ENGINE, "-I", SRC, "-I", GEN, "-ffreestanding", "-nostdlib", "-fno-builtin", "-fomit-frame-pointer", "-Wall", "-Wextra", "-Wno-unused-parameter"];
const objs = [];
for (const src of [path.join(SRC, "crt0.s"), path.join(ENGINE, "engine.c"), path.join(GEN, "art_data.c")]) {
  const obj = path.join(OUT, path.basename(src).replace(/\.(c|s)$/, ".o"));
  if (src.endsWith(".s")) run("m68k-elf-as", ["-m68000", src, "-o", obj]);
  else run("m68k-elf-gcc", [...cflags, "-c", src, "-o", obj]);
  objs.push(obj);
}
const elf = path.join(OUT, "engine.elf");
run("m68k-elf-gcc", [...cflags, "-T", path.join(SRC, "link.ld"), ...objs, "-lgcc", "-o", elf, "-Wl,-Map," + path.join(OUT, "engine.map")]);
const disasm = execFileSync("m68k-elf-objdump", ["-d", elf], { encoding: "utf8" });
const risky = disasm.split("\n").filter((l) => {
  const m = /%(a[0-6])@\+,.*%(a[0-6])@\(/.exec(l);
  return m && m[1] === m[2];
});
if (risky.length) throw new Error(`68000 code with a post-increment source and an indexed destination on the same register:\n${risky.join("\n")}`);
const symbols = {};
for (const line of execFileSync("m68k-elf-nm", ["-S", "-n", elf], { encoding: "utf8" }).split("\n")) {
  const f = line.trim().split(/\s+/);
  if (f.length === 4) symbols[f[3]] = { address: parseInt(f[0], 16), size: parseInt(f[1], 16), type: f[2] };
  else if (f.length === 3) symbols[f[2]] = { address: parseInt(f[0], 16), size: 0, type: f[1] };
}
if (!symbols.lab_state) throw new Error("the engine has no lab_state symbol");
const binPath = path.join(OUT, "program.bin");
run("m68k-elf-objcopy", ["-O", "binary", elf, binPath]);
let program = fs.readFileSync(binPath);
if (program.length > DATA_ADDR) throw new Error(`the engine is ${program.length} bytes: it must end before the data at 0x${DATA_ADDR.toString(16)}`);
if (program.length & 1) program = Buffer.concat([program, Buffer.from([0xff])]);

// 3. The Z80 program (plain: Create ROM encrypts it for the board).
const z80Path = path.join(OUT, "sound.bin");
run("z80asm", ["-o", z80Path, path.join(SRC, "sound-qsound.z80")]);
const z80 = fs.readFileSync(z80Path);

// 4. One file: program | sprite tiles | Z80, and the manifest.
const sprites = Buffer.from(gfx.data.subarray(SPRITE_BASE * 128, spriteEnd * 128));
const bin = Buffer.concat([program, sprites, z80]);
const manifest = {
  format: 1,
  set: "slammast",
  dataAddr: DATA_ADDR,
  program: { offset: 0, size: program.length },
  sprites: { offset: program.length, size: sprites.length, code: SPRITE_BASE },
  z80: { offset: program.length + sprites.length, size: z80.length },
  kabuki: "slammast",
  recruits: RECRUIT_SHIRTS,
  spritePalettes,
  sha256: sha(bin),
  lab_state: symbols.lab_state,
  symbols,
};
const json = JSON.stringify(manifest, null, 1) + "\n";
fs.writeFileSync(path.join(OUT, "engine.bin"), bin);
fs.writeFileSync(path.join(OUT, "engine.json"), json);
console.log(`engine: program ${program.length} bytes, sprites ${sprites.length} bytes (tiles 0x${SPRITE_BASE.toString(16)}-0x${spriteEnd.toString(16)}), z80 ${z80.length} bytes; lab_state at 0x${symbols.lab_state.address.toString(16)}`);

if (CHECK) {
  const same = (name, data) => {
    const p = path.join(PUBLIC, name);
    return fs.existsSync(p) && Buffer.compare(fs.readFileSync(p), Buffer.from(data)) === 0;
  };
  if (!same("engine.bin", bin) || !same("engine.json", json)) {
    console.error("engine: the committed engine differs from this build (run node rom/tools/engine.mjs)");
    process.exit(1);
  }
  console.log("engine: the committed engine matches this build");
} else {
  fs.mkdirSync(PUBLIC, { recursive: true });
  fs.writeFileSync(path.join(PUBLIC, "engine.bin"), bin);
  fs.writeFileSync(path.join(PUBLIC, "engine.json"), json);
  console.log(`engine: wrote ${path.relative(path.resolve(ROOT, ".."), PUBLIC)}/engine.bin and engine.json (sha256 ${manifest.sha256.slice(0, 12)})`);
}
